/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    application
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    // Kotlin Standard Library
    implementation(kotlin("stdlib"))

    // PostgreSQL JDBC Driver
    implementation("org.postgresql:postgresql:42.7.2")

    // Flyway for DB migrations
    implementation("org.flywaydb:flyway-core:11.10.5")
    implementation("org.flywaydb:flyway-database-postgresql:11.10.5")

    // Guava -- TODO CF delete if not needed after compiling
    implementation(libs.guava)

    // Testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.10.2")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // mainClass = "com.bankcore.payments.AppKt"
    mainClass.set("com.bankcore.payments.FlywayMigrateKt")
}

tasks.register<JavaExec>("flywayMigrateManual") {
    group = "flyway"
    description = "Run Flyway migration manually from Kotlin main class"

    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.bankcore.payments.FlywayMigrateKt")
}