/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    application
    id("org.flywaydb.flyway") version "10.10.0" 
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    // Kotlin Standard Library
    implementation(kotlin("stdlib"))

    // PostgreSQL JDBC Driver
    implementation("org.postgresql:postgresql:42.7.2")

    // Flyway for DB migrations
    implementation("org.flywaydb:flyway-core:10.10.0")

    // Guava -- TODO CF delete if not needed after compiling
    implementation(libs.guava)

    // Testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
}

flyway {
    url = "jdbc:postgresql://localhost:5432/bankcore"
    user = "postgres"
    password = "postgres"
    locations = arrayOf("classpath:db/migration")
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.10.2")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "com.bankcore.payments.AppKt"
}
